services:
  - type: web
    name: ai-resume-analyser
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        value: ai-resume-screening-secret-2024
